### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by jewertow** [jewertow/federation#18]
We need a helm chart that will allow to set at least the following values:
```
hub: quay.io/jewertow
tag: latest

controller:
  logLevels:
    mcp: info
    fds: debug

federation:
  exportedServiceSelectors:
  - matchLabels:
      export: "true"
  - matchExpressions:
    - key: app
      operator: In
      values:
      - a
      - b
  remote:
    discovery:
      addresses:
      - 10.244.0.1
      port: 15020
    dataPlane:
      addresses:
      - 10.244.0.2
      port: 15443
```
